//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AccountingEntities : DbContext
    {
        private static AccountingEntities _context;
        public AccountingEntities()
            : base("name=AccountingEntities")
        {
        }

        public static AccountingEntities GetContext()
        {
            if (_context == null)
                _context = new AccountingEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<JobTitle> JobTitles { get; set; }
        public virtual DbSet<Maintenance> Maintenances { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TypeMaintenance> TypeMaintenances { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Отчет> Отчет { get; set; }
    }
}
