//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчет
    {
        public int Idотчета { get; set; }
        public Nullable<int> idоборудование { get; set; }
        public Nullable<int> idсотрудники { get; set; }
        public Nullable<int> idтех_обслуживание { get; set; }
        public Nullable<int> idотдела { get; set; }
    }
}
